# Generated by Django 2.0.7 on 2018-07-14 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=0, on_delete='RESTRICT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(max_length=6, null='true')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='TemporaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default='3', max_length=1)),
                ('skill_id', models.ForeignKey(on_delete='RESTRICT', to='skill_db.Skill')),
                ('user_id', models.ForeignKey(on_delete='RESTRICT', to='skill_db.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(through='skill_db.TemporaryModel', to='skill_db.Skill'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=0, on_delete='RESTRICT', to=settings.AUTH_USER_MODEL),
        ),
    ]
