# Generated by Django 2.0.7 on 2018-07-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='temporarymodel',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='temporarymodel',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(default='null', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(through='skill_db.StudentSkills', to='skill_db.Skill'),
        ),
        migrations.DeleteModel(
            name='TemporaryModel',
        ),
        migrations.AddField(
            model_name='studentskills',
            name='skill_id',
            field=models.ForeignKey(on_delete='RESTRICT', to='skill_db.Skill'),
        ),
        migrations.AddField(
            model_name='studentskills',
            name='user_id',
            field=models.ForeignKey(on_delete='RESTRICT', to='skill_db.Student'),
        ),
    ]
