# Generated by Django 2.0.7 on 2018-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryModel',
            new_name='StudentSkills',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=12),
        ),
    ]
