# Generated by Django 2.0.7 on 2018-07-18 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill_db', '0002_auto_20180714_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.AlterField(
            model_name='studentskills',
            name='lvl',
            field=models.SmallIntegerField(default='3', max_length=1),
        ),
    ]
