# Generated by Django 2.0.7 on 2018-07-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='user_email',
            new_name='teacher_email',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='user_name',
            new_name='teacher_name',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='user_password',
            new_name='teacher_password',
        ),
    ]
