# Generated by Django 2.0.7 on 2018-07-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180711_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.CharField(default='low', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='lvl',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_skills',
        ),
        migrations.AddField(
            model_name='temporarymodel',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Skill'),
        ),
        migrations.AddField(
            model_name='temporarymodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(through='polls.TemporaryModel', to='polls.Skill'),
        ),
    ]
