# Generated by Django 2.0.7 on 2018-07-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180710_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='user_skills',
            field=models.ManyToManyField(to='polls.Skills'),
        ),
    ]
