# Generated by Django 2.0.7 on 2018-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_students_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_lvl',
            field=models.CharField(default='low', max_length=30),
        ),
    ]
