# Generated by Django 2.0.7 on 2018-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180710_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_lvl',
            field=models.CharField(default='low', max_length=30),
        ),
    ]
